In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [21]:
import pandas as pd
import numpy as np

In [4]:
path = '/content/drive/MyDrive/datasets/sonar_dataset.csv'

df = pd.read_csv(path, header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [5]:
df.shape

(208, 61)

In [6]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [8]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [9]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [10]:
X = df.drop(60, axis=1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [11]:
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [12]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5)

R
95   1
103  0
168  0
175  0
31   1

In [13]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [15]:
X_train.shape, X_test.shape

((156, 60), (52, 60))

In [16]:
import tensorflow as tf
from tensorflow import keras

In [29]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 4ms/step - loss: 0.6805 - accuracy: 0.5256
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6719 - accuracy: 0.5385
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6576 - accuracy: 0.7115
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6399 - accuracy: 0.6218
Epoch 5/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6201 - accuracy: 0.7179
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5978 - accuracy: 0.7628
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5712 - accuracy: 0.7564
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5410 - accuracy: 0.7308
Epoch 9/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5410 - accuracy: 0.7244
Epoch 10/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4896 - accuracy: 0.8077
Epoch 11/

In [30]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.4459 - accuracy: 0.8846


[0.4459436535835266, 0.8846153616905212]

In [31]:
y_pred1 = model.predict(X_test)
print(y_pred1[:10])
y_pred = y_pred1.reshape(-1)
print(y_pred[:10])

y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 4ms/step
[[5.3545787e-06]
 [9.9989903e-01]
 [8.3621269e-01]
 [9.9732745e-01]
 [5.7982909e-04]
 [9.6032417e-01]
 [1.0820255e-03]
 [8.5214438e-04]
 [9.9997187e-01]
 [2.5538477e-04]]
[5.3545787e-06 9.9989903e-01 8.3621269e-01 9.9732745e-01 5.7982909e-04
 9.6032417e-01 1.0820255e-03 8.5214438e-04 9.9997187e-01 2.5538477e-04]
[0. 1. 1. 1. 0. 1. 0. 0. 1. 0.]


In [32]:
y_test[:10]

R
161  0
15   1
73   1
96   1
166  0
9    1
100  0
135  0
18   1
148  0

In [33]:
from sklearn.metrics import confusion_matrix, classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.87      0.90        30
           1       0.83      0.91      0.87        22

    accuracy                           0.88        52
   macro avg       0.88      0.89      0.88        52
weighted avg       0.89      0.88      0.89        52



In [34]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5), # dropout layer regularization, after hidden layer
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5), # dropout layer regularization, after hidden layer
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5), # dropout layer regularization, after hidden layer
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 2s 4ms/step - loss: 0.7682 - accuracy: 0.4936
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7342 - accuracy: 0.5256
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7104 - accuracy: 0.5064
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7076 - accuracy: 0.4872
Epoch 5/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6901 - accuracy: 0.5705
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7011 - accuracy: 0.5256
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7204 - accuracy: 0.5128
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6880 - accuracy: 0.5064
Epoch 9/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6818 - accuracy: 0.5449
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7072 - accuracy: 0.5513
Epoch 11/

In [35]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.2505 - accuracy: 0.9423


[0.2505231499671936, 0.942307710647583]

more low cost, which is more good

In [36]:
y_pred1 = model.predict(X_test)
print(y_pred1[:10])
y_pred = y_pred1.reshape(-1)
print(y_pred[:10])

y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 4ms/step
[[0.02567991]
 [0.9383993 ]
 [0.5686323 ]
 [0.89375204]
 [0.04273637]
 [0.7240082 ]
 [0.15957281]
 [0.10717655]
 [0.9966495 ]
 [0.09444393]]
[0.02567991 0.9383993  0.5686323  0.89375204 0.04273637 0.7240082
 0.15957281 0.10717655 0.9966495  0.09444393]
[0. 1. 1. 1. 0. 1. 0. 0. 1. 0.]


In [37]:
from sklearn.metrics import confusion_matrix, classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95        30
           1       0.95      0.91      0.93        22

    accuracy                           0.94        52
   macro avg       0.94      0.94      0.94        52
weighted avg       0.94      0.94      0.94        52

