price = m1 * area + m2 * bedrooms + m3 * age + b

In [13]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [14]:
cols = ['area', 'bedrooms', 'age', 'price']
data = [
    [2600, 3, 20, 550000],
    [3000, 4, 15, 565000],
    [3200, None, 18, 595000],
    [4000, 5, 8, 760000]
]

df = pd.DataFrame(data, columns=cols)
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  595000
3  4000       5.0    8  760000

In [15]:
import pandas as pd

cols = ['area', 'bedrooms', 'age', 'price']
data = [
    [2600, 3, 20, 550000],
    [3000, 4, 15, 565000],
    [3200, None, 18, 610000],
    [3600, 3, 30, 595000],
    [4000, 5, 8, 760000]
]

df = pd.DataFrame(data, columns=cols)

# # Convert the 'bedrooms' column to nullable integer (Int64)
# df['bedrooms'] = df['bedrooms'].astype('Int64')

# Print the dataframe
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      5 non-null      int64  
 1   bedrooms  4 non-null      float64
 2   age       5 non-null      int64  
 3   price     5 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 288.0 bytes


In [17]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [18]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [19]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [20]:
df1 = df.copy()

In [21]:
df1

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [22]:
reg = linear_model.LinearRegression()
reg.fit(df1[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [23]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [24]:
reg.intercept_

383724.9999999998

In [25]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [34]:
137.25*3000 + -26025.*3 +  -6825.*40 + 383724.9999999998

444399.9999999998

## Exercise

In [35]:
pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5569 sha256=bb260ebf517204a24f571b95f5979303aafac6848b6e7a18c689ba991409847d
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [36]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [37]:
# Read the CSV file
csv_file_path = '/content/drive/MyDrive/datasets/hiring.csv'
df = pd.read_csv(csv_file_path)

# Perform operations on the dataframe
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [38]:
from word2number import w2n

In [40]:
df['experience'] = df['experience'].apply(lambda x: w2n.word_to_num(x) if pd.notna(x) else x)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      float64
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(2), int64(2)
memory usage: 384.0 bytes


In [42]:
# Assuming you have a DataFrame called 'df'
columns = df.columns
print(columns)

# to list
# columns_list = df.columns.tolist()
# print(columns_list)

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')


In [44]:
import math
median_testscore = math.floor(df['test_score(out of 10)'].median())
median_experience = math.floor(df.experience.median())
print(median_testscore, median_experience)

8 6


In [45]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_testscore)
df['experience'] = df['experience'].fillna(median_experience)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [46]:
lr = linear_model.LinearRegression()
lr.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [47]:
lr.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [48]:
lr.intercept_

11869.91869918695

In [49]:
lr.predict([[3, 7, 9]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([55983.7398374])