## TensorFlow's Hello World

In [26]:
# importing library
import tensorflow as tf

In [27]:
# tf.function and AutoGraph
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

In [28]:
# print tensor a
a 

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [29]:
# print the value of tensor a
tf.print(a.numpy()[0])

2


In [30]:
"""
Annotating the python functions with tf.function uses TensorFlow Autograph to 
create a TensorFlow static execution graph for the function. tf.function 
annotation tells TensorFlow Autograph to transform function add into TensorFlow 
control flow, which then defines the TensorFlow static execution graph.
"""
@tf.function
def add(a, b):
  c = tf.add(a, b)
  # c = a + b is also a way to define the sum of the terms
  print(c)
  return c

In [31]:
result = add(a, b)
tf.print(result[0])

Tensor("Add:0", shape=(1,), dtype=int32)
5


### Defining multidimensional arrays using TensorFlow

Summarizing:<br><br>

<table style="width:100%">
  <tr>
    <td><b>Dimension</b></td>
    <td><b>Physical Representation</b></td> 
    <td><b>Mathematical Object</b></td>
    <td><b>In Code</b></td>
  </tr>
  
  <tr>
    <td>Zero </td>
    <td>Point</td> 
    <td>Scalar (Single Number)</td>
    <td>[ 1 ]</td>
  </tr>

  <tr>
    <td>One</td>
    <td>Line</td> 
    <td>Vector (Series of Numbers) </td>
    <td>[ 1,2,3,4,... ]</td>
  </tr>
  
   <tr>
    <td>Two</td>
    <td>Surface</td> 
    <td>Matrix (Table of Numbers)</td>
       <td>[ [1,2,3,4,...], [1,2,3,4,...], [1,2,3,4,...],... ]</td>
  </tr>
  
   <tr>
    <td>Three</td>
    <td>Volume</td> 
    <td>Tensor (Cube of Numbers)</td>
    <td>[ [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...] ,...]... ]</td>
  </tr>
  
</table>


In [45]:
Scalar = tf.constant(2)
Vector = tf.constant([5, 6, 2])
Matrix = tf.constant([[1, 2, 3], [2, 3, 4], [5, 6, 7]])
Tensor = tf.constant([ [[1, 2, 3],[2, 3, 4],[3, 4, 5]], [[4, 5, 6],[5, 6, 7],[6, 7, 8]], [[7, 8, 9],[8, 9, 10],[9, 10, 11]] ])

print(f"""Scalar (1 entry): 
{Scalar}\n""")
print(f"""Scalar (3 entries): 
{Vector}\n""")
print(f"""Scalar (3x3 entries): 
{Matrix}\n""")
print(f"""Scalar (3x3x3 entries): 
{Tensor}""")

print("\n====================\n")

print ("Scalar (1 entry):\n %s \n" % Scalar)

print ("Vector (3 entries) :\n %s \n" % Vector)

print ("Matrix (3x3 entries):\n %s \n" % Matrix)

print ("Tensor (3x3x3 entries) :\n %s \n" % Tensor)


Scalar (1 entry): 
2

Scalar (3 entries): 
[5 6 2]

Scalar (3x3 entries): 
[[1 2 3]
 [2 3 4]
 [5 6 7]]

Scalar (3x3x3 entries): 
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 

Vector (3 entries) :
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 

Matrix (3x3 entries):
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [5 6 7]], shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



In [33]:
# tf.shape returns the shape of our data structure.
Scalar.shape

TensorShape([])

In [34]:
Tensor.shape

TensorShape([3, 3, 3])

In [35]:
Matrix_one = tf.constant([[1, 2, 3],[2, 3, 4],[3, 4, 5]])
Matrix_two = tf.constant([[2,2,2], [2,2,2], [2,2,2]])

@tf.function
def add():
  add_1_operation = tf.add(Matrix_one, Matrix_two)
  return add_1_operation

print("Defined using tensorflow function:")
add_1_operation = add()
print(add_1_operation)
print()
print("Defined using normal expressions:")
add_2_operation = Matrix_one + Matrix_two
print(add_2_operation)

Defined using tensorflow function:
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)

Defined using normal expressions:
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [38]:
Matrix_one = tf.constant([[1,2], [3,4]])
Matrix_two = tf.constant([[5,6], [7,8]])

@tf.function
def mathmul():
  return tf.matmul(Matrix_one, Matrix_two)

mul_operation = mathmul()

print("Defined using TensorFlow function:")
print(mul_operation)

Defined using TensorFlow function:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### Variables

In [39]:
v = tf.Variable(0)

In [40]:
@tf.function
def increment_by_one(v):
  v = tf.add(v, 1)
  return v

In [41]:
for i in range(3):
  v = increment_by_one(v)
  print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


## Operations

In [47]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a, b)
d = tf.subtract(a, b)

print ('c =: %s' % c)
print ('d =: %s' % d)


c =: tf.Tensor([7], shape=(1,), dtype=int32)
d =: tf.Tensor([3], shape=(1,), dtype=int32)
